### ISSUE TITLE
C++

### ISSUE THREAD

**Issue by Milalaa** [clicheeeeee/FreSCo#2]
Thanks for sharing! When will the C++ language version be released please? Also what are the benefits of writing in matlab?

**Comment by soytony** [comment]
Planning to finish the Cpp version before the end of this year. But it's not guaranteed as I am currently quite busy. /
It's written in matlab in the first place because it's easier to debug the code and visualize the data that way. 

Thank you for your attention tho!

**Comment by CaptainCplus** [comment]
I Do Not Know, The Only Version I Know (this is stupid BTW) is c++11

**Comment by CaptainCplus** [comment]
Will There Be New Iostream Tools in      
C++ ? I Just Thought There Should Be  More Ways That I Can (or the rest of the c++ community) Have More Options That Might Make It Easier.
Cheers!
